name: Run nix-outdated

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build the application
        run: go build -o nix-outdated main.go

      - name: Run the application
        run: ./nix-outdated ${{ vars.MAINTAINERS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-txt
          path: result.txt
          if-no-files-found: error
          archive: false

      - name: Send mail
        uses: dawidd6/action-send-mail@v16
        with:
          connection_url: "${{secrets.MAIL_CONNECTION}}"
          subject: nix-outdated
          from: ${{vars.MAIL_FROM}}
          to: ${{vars.MAIL_TO}}
          body: Please see attachment
          attachments: results-nopr.txt
